// <auto-generated />
using System;
using Magalog.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Magalog.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Magalog.Domain.Entitites.Order", b =>
                {
                    b.Property<int>("Order_id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Order_id", "Date");

                    b.HasIndex("User_id");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Magalog.Domain.Entitites.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Order_id")
                        .HasColumnType("int");

                    b.Property<int>("Product_id")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Order_id", "Date");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("Magalog.Domain.Entitites.User", b =>
                {
                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("User_Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Magalog.Domain.Entitites.Order", b =>
                {
                    b.HasOne("Magalog.Domain.Entitites.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("User_id")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Magalog.Domain.Entitites.OrderItem", b =>
                {
                    b.HasOne("Magalog.Domain.Entitites.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("Order_id", "Date")
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Magalog.Domain.Entitites.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Magalog.Domain.Entitites.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
